# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tribeared
email: tribeared@protonmail.ch
description: > # this means to ignore newlines until "baseurl:"
  This site's code is available at "https://github.com/tribeared/tribeared.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tribeared
github_username:  tribeared

# Build settings
markdown: kramdown
